variables:
  GIT_SUBMODULE_STRATEGY: normal

image:
  name: ghcr.io/hm-aemy/iic-osic-tools:latest
  entrypoint: [""]

build:
  stage: build

  script:
    - source ~/.bashrc
    - cd simulation && make build-verilator 2>&1 | tee build.log

  artifacts:
    paths:
      - simulation/obj_dir/Vtb_hatch
      - simulation/build.log

smoketest:
  stage: test

  script:
    - source ~/.bashrc
    - cd simulation && make sim-verilator 2>&1 | tee sim.log

  artifacts:
    paths:
      - simulation/hatch.fst
      - simulation/sim.log