variables:
  GIT_SUBMODULE_STRATEGY: normal

image:
  name: ghcr.io/hm-aemy/iic-osic-tools:latest
  entrypoint: [""]

build-sim:
  stage: build

  script:
    - source ~/.bashrc
    - cd simulation && make build-verilator 2>&1 | tee build.log

  artifacts:
    paths:
      - simulation/obj_dir/Vtb_hatch
      - simulation/build.log

smoketest:
  stage: test

  script:
    - source ~/.bashrc
    - cd simulation && make sim-verilator 2>&1 | tee sim.log
    
.run-software-template:
  stage: test

  script:
    - source ~/.bashrc
    - cd software/${APP}
    - mkdir -p build
    - cd build
    - cmake .. -DCMAKE_TOOLCHAIN_FILE=../../riscv32.cmake
    - make
    - cd ../../..
    - cd simulation
    - SW_HEX=../software/${APP}/build/${APP}.hex make sim-verilator 2>&1 | tee sim.log

  artifacts:
    paths:
      - software/${APP}/build/${APP}.{elf,dis,hex}
      - simulation/hatch.fst
      - simulation/sim.log
    name: "${APP}-artifacts"

run-software:
  extends: .run-software-template
  parallel:
    matrix:
      - APP: ["hello", "smoketest"]
