variables:
  GIT_SUBMODULE_STRATEGY: normal

image:
  name: ghcr.io/hm-aemy/iic-osic-tools:latest
  entrypoint: [""]

build-sim:
  stage: build

  script:
    - source ~/.bashrc
    - cd simulation && make build-verilator 2>&1 | tee build.log

  artifacts:
    paths:
      - simulation/obj_dir/Vtb_hatch
      - simulation/build.log

.build-software-template:
  stage: build
  script:
    - source ~/.bashrc
    - cd software/${APP}; mkdir -p build; cd build; cmake .. -DCMAKE_TOOLCHAIN_FILE=../../riscv32.cmake; make
  artifacts:
    paths:
      - software/${APP}/build/${APP}.{elf,dis,hex}

build-software:
  extends: .build-software-template
  parallel:
    matrix:
      - APP: ["hello", "smoketest"]

smoketest:
  stage: test

  script:
    - source ~/.bashrc
    - cd simulation && make sim-verilator 2>&1 | tee sim.log

  artifacts:
    paths:
      - simulation/hatch.fst
      - simulation/sim.log